export const GET_MOVIEDATA_REQ="GET_MOVIEDATA_REQ"
export const GET_MOVIEDATA_SUCCESS="GET_MOVIEDATA_SUCCESS"
export const GET_MOVIEDATA_FAILURE="GET_MOVIEDATA_FAILURE"


export const GET_SINGLE_MOVIEDATA_REQ="GET_SINGLE_MOVIEDATA_REQ"
export const GET_SINGLE_MOVIEDATA_SUCCESS="GET_SINGLE_MOVIEDATA_SUCCESS"
export const GET_SINGLE_MOVIEDATA_FAILURE="GET_SINGLE_MOVIEDATA_FAILURE"


export const SET_QUERY="SET_QUERY";